### ISSUE TITLE
Crash report. 崩溃报告.

### ISSUE THREAD

**Issue by chenenyu** [byteam/delta#2]
If your app crashed when testing, please report it at here with enough information.  
如果在测试的过程中发生崩溃，请在该issue中提交完善的崩溃信息(机型、系统版本、版本号、log等)。

**Comment by SilenceDut** [comment]
魅族MX Pro5

DELTA_VERSION=0.0.1 

java.lang.RuntimeException: Delta optimization failed (Method makeDexElements with parameters [interface java.util.List, class java.io.File, interface java.util.List] not found in class dalvik.system.DexPathList).
                      at org.byteam.delta.Delta.applyPatch(Delta.java:138)
                      at org.byteam.delta.Delta.applyPatchFromDevice(Delta.java:65)
                      at org.byteam.delta.sample.MainActivity.onClick(MainActivity.java:35)

**Comment by chenenyu** [comment]
@SilenceDut 请问系统版本是多少？

**Comment by SilenceDut** [comment]
Android 5.1,  魅族Flyme 5.1.9.0A

**Comment by chenenyu** [comment]
@SilenceDut 我看看能不能借到这款机器，请稍后。如果能加入qq群271849001参与测试就更好了。

**Comment by chenenyu** [comment]
@SilenceDut  0.0.2已修复，欢迎测试反馈

**Comment by SilenceDut** [comment]
@chenenyu 已通过验证

**Comment by baiting123** [comment]
Failure to verify dex file '/data/data/org.byteam.delta.sample/files/delta_patched/classes.dex': Bad file size (1570044, expected 780d)

**Comment by chenenyu** [comment]
@baiting123 这个问题一般是生成补丁的操作流程不正确   建议看下wiki   或者加入qq群讨论
